CREATE TABLE "platform_settings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"site_name" text DEFAULT 'Energized' NOT NULL,
	"site_description" text,
	"site_email" text,
	"site_phone" text,
	"site_address" text,
	"site_logo" text,
	"site_favicon" text,
	"maintenance_mode" boolean DEFAULT false NOT NULL,
	"allow_registration" boolean DEFAULT true NOT NULL,
	"require_email_verification" boolean DEFAULT true NOT NULL,
	"password_min_length" integer DEFAULT 8 NOT NULL,
	"session_timeout_hours" integer DEFAULT 24 NOT NULL,
	"max_login_attempts" integer DEFAULT 5 NOT NULL,
	"lockout_duration_minutes" integer DEFAULT 30 NOT NULL,
	"email_from_name" text,
	"email_from_address" text,
	"email_reply_to" text,
	"admin_notification_email" text,
	"enable_sms" boolean DEFAULT false NOT NULL,
	"google_analytics_id" text,
	"stripe_publishable_key" text,
	"social_links" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
